name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Use the latest version

      - name: Deploy to main branch
        run: |
          git add .
          git commit -m "Deploy to main branch"
          git push
